version: '3'

services: 
    backend_app:
        build: 
            context: .
            dockerfile: /backend_server/Dockerfile
        container_name: "backend_app"
        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes: .:/backend_app
        ports: 
            -"8000:8000"
        
    frontend_app:
        build: 
            context: .
            dockerfile: /frontend/Dockerfile
        container_name: "frontend_app"
        volumes: .:/frontend_app
        ports: 
            - "3000:3000"