# Generated by Django 3.2 on 2021-06-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_alter_music_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="video",
            field=models.FileField(upload_to="videos/musics"),
        ),
    ]
