# Generated by Django 3.2 on 2021-06-17 06:41

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_alter_music_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="video",
            field=models.FileField(upload_to=music.models.unique_user_path),
        ),
    ]
