# Generated by Django 3.2 on 2021-09-21 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import literature.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tag", "0001_initial"),
        ("literature", "0003_auto_20210807_1427"),
    ]

    operations = [
        migrations.CreateModel(
            name="DragDropSelectBook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "thumbnail_pic",
                    models.ImageField(blank=True, null=True, upload_to=literature.models.unique_file_path),
                ),
                ("rating", models.FloatField(default=0.0)),
                ("description", models.CharField(max_length=300)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("asm", "Assamese"),
                            ("bn", "Bengali"),
                            ("en", "English"),
                            ("gu", "Gujarati"),
                            ("hi", "Hindi"),
                            ("kha", "Khasi"),
                            ("kn", "Kannada"),
                            ("kok", "Konkani"),
                            ("lus", "Lushai"),
                            ("ml", "Malayalam"),
                            ("mr", "Marathi"),
                            ("mni", "Meitei"),
                            ("nep", "Nepali"),
                            ("ori", "Oriya"),
                            ("pan", "Panjabi"),
                            ("ta", "Tamil"),
                            ("te", "Telugu"),
                            ("ur", "Urdu"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "catagory",
                    models.CharField(
                        choices=[
                            ("com", "comedy"),
                            ("cri", "crime"),
                            ("fic", "fiction"),
                            ("sus", "suspense"),
                            ("hor", "horror"),
                            ("mys", "mystry"),
                            ("oth", "others"),
                            ("rom", "romance"),
                        ],
                        max_length=50,
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("number_of_contents", models.PositiveIntegerField(default=0)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="chapter",
            options={"ordering": ["updated_at"]},
        ),
        migrations.RenameField(
            model_name="chapter",
            old_name="date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="chapter",
            old_name="front_img",
            new_name="thumbnail_pic",
        ),
        migrations.RenameField(
            model_name="novel",
            old_name="date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="novel",
            old_name="front_img",
            new_name="thumbnail_pic",
        ),
        migrations.RenameField(
            model_name="poem",
            old_name="date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="poem",
            old_name="front_img",
            new_name="thumbnail_pic",
        ),
        migrations.RenameField(
            model_name="story",
            old_name="date",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="story",
            old_name="front_img",
            new_name="thumbnail_pic",
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="author",
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="tags",
        ),
        migrations.AddField(
            model_name="chapter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="novel",
            name="catagory",
            field=models.CharField(
                choices=[
                    ("com", "comedy"),
                    ("cri", "crime"),
                    ("fic", "fiction"),
                    ("sus", "suspense"),
                    ("hor", "horror"),
                    ("mys", "mystry"),
                    ("oth", "others"),
                    ("rom", "romance"),
                ],
                default="hor",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="novel",
            name="description",
            field=models.CharField(
                default="This is the description for all the literatures i have created till now and I have no regret for that. May you go to hel",
                max_length=300,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="novel",
            name="language",
            field=models.CharField(
                choices=[
                    ("asm", "Assamese"),
                    ("bn", "Bengali"),
                    ("en", "English"),
                    ("gu", "Gujarati"),
                    ("hi", "Hindi"),
                    ("kha", "Khasi"),
                    ("kn", "Kannada"),
                    ("kok", "Konkani"),
                    ("lus", "Lushai"),
                    ("ml", "Malayalam"),
                    ("mr", "Marathi"),
                    ("mni", "Meitei"),
                    ("nep", "Nepali"),
                    ("ori", "Oriya"),
                    ("pan", "Panjabi"),
                    ("ta", "Tamil"),
                    ("te", "Telugu"),
                    ("ur", "Urdu"),
                ],
                default="en",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="novel",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="novel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="novel",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="poem",
            name="catagory",
            field=models.CharField(
                choices=[
                    ("com", "comedy"),
                    ("cri", "crime"),
                    ("fic", "fiction"),
                    ("sus", "suspense"),
                    ("hor", "horror"),
                    ("mys", "mystry"),
                    ("oth", "others"),
                    ("rom", "romance"),
                ],
                default="mys",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poem",
            name="description",
            field=models.CharField(
                default="This is the description for all the literatures i have created till now and I have no regret for that. May you go to hel",
                max_length=300,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poem",
            name="language",
            field=models.CharField(
                choices=[
                    ("asm", "Assamese"),
                    ("bn", "Bengali"),
                    ("en", "English"),
                    ("gu", "Gujarati"),
                    ("hi", "Hindi"),
                    ("kha", "Khasi"),
                    ("kn", "Kannada"),
                    ("kok", "Konkani"),
                    ("lus", "Lushai"),
                    ("ml", "Malayalam"),
                    ("mr", "Marathi"),
                    ("mni", "Meitei"),
                    ("nep", "Nepali"),
                    ("ori", "Oriya"),
                    ("pan", "Panjabi"),
                    ("ta", "Tamil"),
                    ("te", "Telugu"),
                    ("ur", "Urdu"),
                ],
                default="en",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poem",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="poem",
            name="read_time",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="poem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="poem",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="story",
            name="catagory",
            field=models.CharField(
                choices=[
                    ("com", "comedy"),
                    ("cri", "crime"),
                    ("fic", "fiction"),
                    ("sus", "suspense"),
                    ("hor", "horror"),
                    ("mys", "mystry"),
                    ("oth", "others"),
                    ("rom", "romance"),
                ],
                default="mys",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="story",
            name="description",
            field=models.CharField(
                default="This is the description for all the literatures i have created till now and I have no regret for that. May you go to hel",
                max_length=300,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="story",
            name="language",
            field=models.CharField(
                choices=[
                    ("asm", "Assamese"),
                    ("bn", "Bengali"),
                    ("en", "English"),
                    ("gu", "Gujarati"),
                    ("hi", "Hindi"),
                    ("kha", "Khasi"),
                    ("kn", "Kannada"),
                    ("kok", "Konkani"),
                    ("lus", "Lushai"),
                    ("ml", "Malayalam"),
                    ("mr", "Marathi"),
                    ("mni", "Meitei"),
                    ("nep", "Nepali"),
                    ("ori", "Oriya"),
                    ("pan", "Panjabi"),
                    ("ta", "Tamil"),
                    ("te", "Telugu"),
                    ("ur", "Urdu"),
                ],
                default="en",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="story",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="story",
            name="read_time",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="story",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="story",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.AddField(
            model_name="dragdropselectbook",
            name="novels",
            field=models.ManyToManyField(blank=True, to="literature.Novel"),
        ),
        migrations.AddField(
            model_name="dragdropselectbook",
            name="poems",
            field=models.ManyToManyField(blank=True, to="literature.Poem"),
        ),
        migrations.AddField(
            model_name="dragdropselectbook",
            name="stories",
            field=models.ManyToManyField(blank=True, to="literature.Story"),
        ),
        migrations.AddField(
            model_name="dragdropselectbook",
            name="tags",
            field=models.ManyToManyField(blank=True, to="tag.Tag"),
        ),
    ]
