# Generated by Django 3.2 on 2021-06-18 05:02

from django.db import migrations, models
import recitation.models


class Migration(migrations.Migration):

    dependencies = [
        ("recitation", "0002_alter_recitation_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recitation",
            name="front_img",
            field=models.ImageField(blank=True, null=True, upload_to=recitation.models.unique_front_img),
        ),
        migrations.AlterField(
            model_name="recitation",
            name="recitation_audio",
            field=models.FileField(upload_to=recitation.models.unique_recitation_audio),
        ),
    ]
