# Generated by Django 3.2 on 2021-08-07 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recitation", "0003_auto_20210618_0502"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recitation",
            name="reciter",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
