# Generated by Django 3.2 on 2021-06-10 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tag", "0001_initial"),
        ("api_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Art",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50)),
                ("image", models.ImageField(blank=True, upload_to="")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("artist", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api_app.hemontikauser")),
                ("tags", models.ManyToManyField(blank=True, to="tag.Tag")),
            ],
        ),
    ]
