# Generated by Django 3.2 on 2021-06-18 05:02

import art.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art", "0003_alter_art_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="art",
            name="image",
            field=models.ImageField(upload_to=art.models.unique_art_image),
        ),
    ]
