# Generated by Django 3.2 on 2021-09-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art", "0005_alter_art_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="country",
            field=models.CharField(
                blank=True, choices=[("IN", "INDIA"), ("USA", "UNITED sTATES")], max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="art",
            name="description",
            field=models.CharField(default="this is the description", max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="art",
            name="district",
            field=models.CharField(
                blank=True, choices=[("HOW", "HOWRAH"), ("HOO", "HOOGLY"), ("KOL", "KOLKATA")], max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="art",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="art",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[("WB", "WEST BENGAL"), ("UP", "UTTAR PRADESH"), ("MP", "MADHYA PRADESH"), ("TN", "TAMILNADU")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="art",
            name="views",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
