LANGUAGE_CHOICES = [
    ('asm', 'Assamese'),
    ('bn', 'Bengali'),
    ('en', 'English'),
    ('gu', 'Gujarati'),
    ('hi', 'Hindi'),
    ('kha', 'Khasi'),
    ('kn', 'Kannada'),
    ('kok', 'Konkani'),
    ('lus', 'Lushai'),
    ('ml', 'Malayalam'),
    ('mr', 'Marathi'),
    ('mni', 'Meitei'),
    ('nep', 'Nepali'),
    ('ori', 'Oriya'),
    ('pan', 'Panjabi'),
    ('ta', 'Tamil'),
    ('te', 'Telugu'),
    ('ur', 'Urdu'),
]

CATAGORY_CHOICES = [
    ('com', 'comedy'),
    ('cri', 'crime'),
    ('fic', 'fiction'),
    ('sus', 'suspense'),
    ('hor', 'horror'),
    ('mys', 'mystry'),
    ('oth', 'others'),
    ('rom', 'romance'),
]